final List<Map<String, String>> children = [
  {
    'name': 'الطفل الأول',
    'age': '22',
    'foundBy': 'أحمد',
    'foundDate': '31/12/2023',
    'status': 'يعاني من متلازمة داون',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'دينا',
    'age': '22',
    'foundBy': 'مدني',
    'foundDate': '2/2/2024',
    'status': 'تعاني من الزهايمر',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'ليان',
    'age': '25',
    'foundBy': 'شرطة',
    'foundDate': '16/1/2024',
    'status': 'تعاني من إعاقة ذهنية',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'نهى',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'هدى',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'نور',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'دعاء',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
];
final List<Map<String, String>> allData = [
  {
    'name': 'الطفل الأول',
    'age': '22',
    'foundBy': 'أحمد',
    'foundDate': '31/12/2023',
    'status': 'يعاني من متلازمة داون',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'دينا',
    'age': '22',
    'foundBy': 'مدني',
    'foundDate': '2/2/2024',
    'status': 'تعاني من الزهايمر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'ليان',
    'age': '25',
    'foundBy': 'شرطة',
    'foundDate': '16/1/2024',
    'status': 'تعاني من إعاقة ذهنية',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'نهى',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'هدى',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'نور',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'دعاء',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
];
final List<Map<String, String>> recentData = [
  {
    'name': 'الطفل الأول',
    'age': '22',
    'foundBy': 'أحمد',
    'foundDate': '31/12/2023',
    'status': 'يعاني من متلازمة داون',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'دينا',
    'age': '22',
    'foundBy': 'مدني',
    'foundDate': '2/2/2024',
    'status': 'تعاني من الزهايمر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'ليان',
    'age': '25',
    'foundBy': 'شرطة',
    'foundDate': '16/1/2024',
    'status': 'تعاني من إعاقة ذهنية',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'نهى',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'هدى',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'نور',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
  {
    'name': 'دعاء',
    'age': '7',
    'foundBy': 'مدني',
    'foundDate': '16/5/2024',
    'status': 'قاصر',
    'gender': 'امرأه',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/person.jpg',
  },
];

final List<Map<String, String>> police = [
  {
    'stationName': 'قسم شرطة الجيزة',
    'address': 'شارع الهرم، الجيزة',
    'phoneNumber': '0123456789',
    'area': 'الجيزة',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/station.jpg',
  },
  {
    'stationName': 'قسم شرطة المعادي',
    'address': 'شارع النصر، المعادي',
    'phoneNumber': '0112345678',
    'area': 'المعادي',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/station.jpg',
  },
  {
    'stationName': 'قسم شرطة مدينة نصر',
    'address': 'شارع الطيران، مدينة نصر',
    'phoneNumber': '0101234567',
    'area': 'مدينة نصر',
    'imageUrl': 'https://i.ibb.co/3zBpjgh/station.jpg',
  },
];
